### ISSUE TITLE
Problem z DSJ odpalanym z pliku .bat z prekonfiguracją.

### ISSUE THREAD

**Issue by ernestrudziec** [Mtik333/DSJ2Trainer#1]
Nie wiem czy koniecznym jest sprawdzanie czy w DosBoxie jest odpalony DSJ2, albo chociaż przydałby się jakiś backdoor żeby ominąć to sprawdzenie... Bo mam odpalonego DSJ w dosboxie ewidentnie ale Trainer go nie widzi. Co najlepsze wczoraj grałem i łapało, dziś nagle nie, nie widzę zależności. Firewall wyłączony, dosbox zainstalowany, a nie portable - ale na portable ten sam problem.

**Comment by ernestrudziec** [comment]
Znalazłem rozwiązanie. Warto wspomnieć w "Pomocy" trainera, że na starszym niż  0.74-3 DOSboxie trainer nie działa i nie znajduje odpalonego DSJ'a. W więszkości dostępnych paczek z DSJ'em w sieci jest pakowany od razu DSJ 0.73.

**Comment by Mtik333** [comment]
Możesz mi podrzucić tą paczkę z DSJem, której używasz?

**Comment by ernestrudziec** [comment]
Już chyba problem rozwiązany, kwestia wersji dosboxa. Morze dorzuć error
catch na jego wersje, żeby trainer ruszał tylko z Dosboxem 0.74-3.

**Comment by Mtik333** [comment]
Wiesz co, wolałbym jednak spróbować zrobić tak, żeby i na starszych wersjach DOSBoxa to śmigało, więc gdybyś mógł jakoś mi podrzucić tę paczkę, której sam używasz, byłbym wdzięczny.

**Comment by ernestrudziec** [comment]
https://chomikuj.pl/Sharly/Deluxe+Ski+Jump+2.1+*5bWINDOWS+10*5d

http://chomikuj.pl/adamus.ap/7.Gry/DSJ+2.1+(dzia*c5*82aj*c4*85ce+na+vista+i+7)



>

**Comment by Mtik333** [comment]
No rzeczywiście nie śmiga, spróbuję popatrzeć co takiego się dzieje, że w 0.73 jest już problem z wykryciem DSJa.

**Comment by Mtik333** [comment]
> 
> https://chomikuj.pl/Sharly/Deluxe+Ski+Jump+2.1+*5bWINDOWS+10*5d http://chomikuj.pl/adamus.ap/7.Gry/DSJ+2.1+(dzia*c5*82aj*c4*85ce+na+vista+i+7)
> […](#)

Okej, wydaje mi się, że naprawiłem problem w wersji 0.73, ale będę musiał dorobić jakiś wyjątek na wypadek gdyby ktoś odpalił wersję inną niż 0.73 lub 0.74, do końca tygodnia prawdopodobnie będzie to gotowe.

**Comment by ernestrudziec** [comment]
No i gitara 👍

**Comment by Mtik333** [comment]
Wrzuciłem w release'ach wersję 1.3 która dodaje wsparcie dla DOSBoxa 0.73, daj znać czy działa.

**Comment by Mtik333** [comment]
Skoro nie ma odezwu, to zamykam
