### ISSUE TITLE
Adresy komórek pamięci dla kierunku i siły wiatru

### ISSUE THREAD

**Issue by Kolejarz** [Mtik333/DSJ2Trainer#3]
Cześć, pytanie niezwiązane bezpośrednio z trainerem, a raczej sposobem na znalezienie adresów, pod którymi kryją się wartości odpowiadające za wiatr :) Zasadniczo chciałbym osiągnąć podobny efekt - możliwość kontroli kierunku i siły wiatru, ale po krótkiej zabawie z DosBoxem i Cheat Engine nie mogę znaleźć adresów, które odpowiadają za te wartości.

Mógłbyś krótko opisać sposób w jaki znalazłeś odpowiednie komórki w pamięci emulatora?

**Comment by Mtik333** [comment]
Cóż, nie wiem czy uda się krótko.

Wpierw to chyba było głównie kombinowanie z pauzowaniem gry i sprawdzaniem siły wiatru. Na początku znalazłem tę główną wartość, ale po chwili kombinowania z ustawianiem tej wartości, skoczek nie zachowywał się tak jak spodziewałem - nie jestem w stanie powiedzieć jak dokładnie, ale odkryłem, że w bliskiej odległości są jeszcze dwie komórki. Po "wirtualnych obliczeniach" wyszło mi, że na siłę wiatru składają się składowa pionowa i składowa pozioma - potem z nich zwykły Pitagoras (a^2 + b^2 = c^2) robił tę "złożoną" siłę wiatru.

Potem zacząłem kombinować z kierunkiem wiatru i znowu miałem jakieś problemy, żeby zrozumieć co się tam znajduje - wyszło, że kierunek wiatru to w zasadzie kąt od 0 do 360, gdzie 0 odpowiadało chyba za dmuchanie w prawo.

Jest tam jeszcze kilka dziwnych miejsc w pamięci: wariancje do siły wiatru/kierunku wiatru (żeby symulować "dynamicznie zmieniające się warunku") - obie ustawiam na 0 - oraz chyba stałą liczbę Pi jako "idealny kierunek wiatru".

Mając już tą wiedzę, zacząłem szukać jakichś elementów w pamięci, które pozwolą mi jakoś przejść do tego bloku obliczania siły wiatru. W pamięci znajduje się komentarz //DSJ_v2.00// i występuje przy odpalonej grze bodaj 3 razy, przy czym skorzystałem z tylko jednego wystąpienia, bo pozwala mi określać, czy gra jest wciąż załadowana czy już nie (tak żeby trainer automatycznie wyłączył się). 
Po kilkunastu próbach okazało się, że o ile DOSBox za każdym razem zmienia miejsce w którym rozpoczyna się blok pamięci DeSeJota, tak komórki ze zmiennymi do siły/kierunku wiatru pozostają w tej samej odległości do tej komórki z komentarzem //DSJ_v2.00//, stąd wystarczyło już tylko sobie w kodzie zapisać te odległości heksadecymalnie.

Po drodze jeszcze znalazłem na tej samej zasadzie coś, co udaje odległość skoczka od zeskoku oraz prędkość skoczka, też poprzez obserwację tych zmieniających się komórek.

No i to chyba tyle. Mogę podrzucić link do kodu, który trzymam na Bitbucket, nie wiem czy ułatwi to zrozumienie, ale będzie chyba lepiej widać, co ja tam wyprawiam.

**Comment by Kolejarz** [comment]
wow, dzięki za informacje! :) link na pewno nie zaszkodzi - co do wiatru też namierzyłem jedną komórkę, której zmiany w miarę odpowiadały wahaniom wiatru, ale po zablokowaniu wartości strzałka dalej "skakała" - teraz już rozumiem, że pewnie blokowałem tylko jedną ze składowych :D (w sumie jakby o tym pomyśleć, to takie rozwiązanie tego w kodzie gry ma spory sens)

do przeglądania pamięci korzystasz z CheatEngine czy jakiegoś dedykowanego narzędzia dla DOS?

**Comment by Mtik333** [comment]
Wszystko robiłem z pomocą Cheat Engine - miałem przez chwilę myśl żeby dać wsparcie do odpalania DSJ2 na Windowsie XP, ale że korzystam z Javy 8, a nie potrafiłem jej zainstalować na wirtualnej maszynie z tym systemem i nie chciało mi się robić downgrade do Javy 7, porzuciłem pomysł więc do działania trainera wymagany jest DOSBox.

Masz konto na Bitbucket? Z tego co pamiętam, ustawiłem tam repozytorium jako prywatne, więc nie wiem czy je zobaczysz wchodząc tu: [Repo](https://bitbucket.org/mtik333/dsj2trainer/src/master/)

**Comment by Kolejarz** [comment]
Powinienem mieć jakieś konto pod nazwą 'kolejarz' albo 'coleyash' - postaram się sprawdzić po weekendzie

**Comment by Mtik333** [comment]
Okej, w takim razie czekam.

**Comment by Mtik333** [comment]
> 
> 
> Powinienem mieć jakieś konto pod nazwą 'kolejarz' albo 'coleyash' - postaram się sprawdzić po weekendzie

To jak, udało się ten profil znaleźć?

**Comment by Mtik333** [comment]
> 
> 
> Powinienem mieć jakieś konto pod nazwą 'kolejarz' albo 'coleyash' - postaram się sprawdzić po weekendzie

Ponownie pinguję zwłaszcza że wyjszła wersja 1.3.2.

**Comment by Kolejarz** [comment]
Przepraszam, projekt poszedł w odstawkę, a maile z powiadomieniami z GitHuba lądowały w innym folderze :P
Założyłem nowe konto: kolejarz@outlook.com

W międzyczasie Jussi wydał DSJ 2 na Androida - zastanawiam się czy czytanie i modyfikacje pamięci nie byłyby łatwiejsze w tym środowisku?

**Comment by Mtik333** [comment]
> kolejarz@outlook.com

Okej, wysłałem "zaproszenie" na tego maila.

Co do wersji na Androida - no właśnie może być tam problem. Nie słyszałem, żeby istniała linuksowa wersja Cheat Engine (tak żeby sprawdzić te adresy) a tym bardziej wersja na Androida. Dalej problem mógłby być z samymi adresami - jeśli nie będą statyczne tak jak w tej wersji "komputerowej", to w zasadzie tu już jest koniec zabawy. Jeśli jednak to wciąż działa podobnie, to trzeba by przemyśleć sposób dobierania się do pamięci procesu w Linuksie - tu pewnie nie ma takiego API jak w Windowsach, nie sprawdzałem czy biblioteka JNA to ogarnie. Jeśli i to udałoby się zrobić, to ostatnim problemem jest napisanie apki - jako że to wciąż Java, nie powinno być dużego problemu, ale mogłem już wyjść z wprawy, bo ostatni raz w Androidzie dziergałem na studiach.

**Comment by Mtik333** [comment]
> 
> 
> Przepraszam, projekt poszedł w odstawkę, a maile z powiadomieniami z GitHuba lądowały w innym folderze :P
> Założyłem nowe konto: [kolejarz@outlook.com](mailto:kolejarz@outlook.com)
> 
> W międzyczasie Jussi wydał DSJ 2 na Androida - zastanawiam się czy czytanie i modyfikacje pamięci nie byłyby łatwiejsze w tym środowisku?

Chyba zapomniałem, jak ostatecznie wyszło z tym zaproszeniem? Dostałeś jakiś link i wgląd do kodu czy nie bardzo?

**Comment by krzys1u** [comment]
@Mtik333 Czy jest opcja dostać zaproszenie na bitbucket żeby popatrzeć sobie do kodu? 
Email: stozekrzysztof@gmail.com

**Comment by Mtik333** [comment]
> 
> 
> @Mtik333 Czy jest opcja dostać zaproszenie na bitbucket żeby popatrzeć sobie do kodu?
> Email: [stozekrzysztof@gmail.com](mailto:stozekrzysztof@gmail.com)

Poleciało zaproszenie.

**Comment by krzys1u** [comment]
@Mtik333 działa dzieki

**Comment by Kolejarz** [comment]
@Mtik333 u mnie też śmiga, zamknę ten ticket, żeby nie zaśmiecał backloga :)
